#!/usr/bin/env bash
# ============================================================================
# Capi Guard — Git History Sanitizer
# Generated by GitHistorySanitizationSkill | DO NOT EDIT MANUALLY
#
# What this script does:
#   1. Validates that a backup branch exists (INTEGRITY CHECK)
#   2. Forces all Laravel-sensitive patterns into .gitignore
#   3. Removes sensitive files from the COMPLETE git history (all branches/tags)
#   4. Blob-replaces detected secrets in history with [REDACTED]
#   5. Runs aggressive garbage collection to purge dangling objects
#
# Requirements:
#   - git filter-repo  (pip install git-filter-repo)
#   - git >= 2.22
#
# Usage:
#   chmod +x sanitize-git-history.sh
#   ./sanitize-git-history.sh
# ============================================================================

set -euo pipefail

REPO_PATH="{{REPO_PATH}}"
BACKUP_BRANCH="{{BACKUP_BRANCH}}"

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Step 0: Pre-flight checks ────────────────────────────────────────────────
info "Pre-flight checks..."

command -v git          >/dev/null 2>&1 || error "git not found in PATH."
command -v git-filter-repo >/dev/null 2>&1 \
  || python3 -m git_filter_repo --version >/dev/null 2>&1 \
  || error "git-filter-repo not found. Install with: pip install git-filter-repo"

cd "${REPO_PATH}"

# Ensure we are on a clean working tree
if ! git diff --quiet || ! git diff --cached --quiet; then
  error "Working tree has uncommitted changes. Commit or stash them before running."
fi

# ── Step 1: Integrity — verify backup branch ─────────────────────────────────
info "Checking backup branch '${BACKUP_BRANCH}'..."
if ! git branch --list "${BACKUP_BRANCH}" | grep -q "${BACKUP_BRANCH}"; then
  error "Backup branch '${BACKUP_BRANCH}' does not exist.\n" \
        "Create it first:\n  git checkout -b ${BACKUP_BRANCH}\n  git checkout -"
fi
info "✔ Backup branch '${BACKUP_BRANCH}' verified."

# ── Step 2: .gitignore enforcement ───────────────────────────────────────────
info "Enforcing Laravel-sensitive .gitignore patterns..."
GITIGNORE_PATTERNS=(
  ".env"
  ".env.*"
  "!.env.example"
  "storage/*.key"
  "auth.json"
  "vendor/"
  ".phpunit.result.cache"
  "public/storage"
  "*.pem"
  "id_rsa"
  "*.key"
  "deploy.php"
)

for pattern in "${GITIGNORE_PATTERNS[@]}"; do
  if ! grep -qxF "${pattern}" .gitignore 2>/dev/null; then
    echo "${pattern}" >> .gitignore
    warn "Added to .gitignore: ${pattern}"
  fi
done

# ── Step 3: Remove sensitive files from FULL history ─────────────────────────
info "Removing sensitive files from entire git history..."

SENSITIVE_FILES=(
{{SENSITIVE_FILES}}
)

if [ ${#SENSITIVE_FILES[@]} -gt 0 ]; then
  FILTER_ARGS=()
  for f in "${SENSITIVE_FILES[@]}"; do
    FILTER_ARGS+=("--path" "${f}")
  done

  git filter-repo \
    "${FILTER_ARGS[@]}" \
    --invert-paths \
    --force
  info "✔ Sensitive files purged from history."
else
  info "No sensitive files found in history — skipping file purge."
fi

# ── Step 4: Blob-replace secrets with [REDACTED] ─────────────────────────────
info "Replacing secrets in history blobs..."

# Build a Python callback script for git filter-repo
CALLBACK_SCRIPT=$(mktemp /tmp/capi_guard_callback_XXXXXX.py)
cat > "${CALLBACK_SCRIPT}" << 'PYTHON_EOF'
import re

SECRET_PATTERNS = [
    # Laravel APP_KEY
    (rb'APP_KEY\s*=\s*base64:[A-Za-z0-9+/=]{40,}', b'APP_KEY=[REDACTED]'),
    # DB credentials
    (rb'DB_PASSWORD\s*=\s*\S+',                     b'DB_PASSWORD=[REDACTED]'),
    (rb'DB_USERNAME\s*=\s*(?!root|homestead)\S+',   b'DB_USERNAME=[REDACTED]'),
    # Redis
    (rb'REDIS_PASSWORD\s*=\s*\S+',                  b'REDIS_PASSWORD=[REDACTED]'),
    # Mail
    (rb'MAIL_PASSWORD\s*=\s*\S+',                   b'MAIL_PASSWORD=[REDACTED]'),
    # Generic secrets
    (rb'(?:API_KEY|SECRET_KEY|AUTH_TOKEN)\s*=\s*\S{8,}', b'SECRET=[REDACTED]'),
    # Hardcoded PHP password strings
    (rb"'password'\s*=>\s*'[^']{3,}'",              b"'password' => '[REDACTED]'"),
    # Staging IPs (excludes 127.x, 10.x, 172.x, 192.168.x, and semver-like x.x.x patterns)
    (
        rb'\b(?!127\.|10\.|172\.|192\.168\.)(?!(?:\d+\.){2}\d+$)(\d{1,3}\.){3}\d{1,3}\b',
        b'[REDACTED_IP]'
    ),
]

def blob_callback(blob):
    content = blob.data
    changed = False
    for pattern, replacement in SECRET_PATTERNS:
        new_content = re.sub(pattern, replacement, content)
        if new_content != content:
            content = new_content
            changed = True
    if changed:
        blob.data = content

PYTHON_EOF

git filter-repo \
  --blob-callback "$(cat "${CALLBACK_SCRIPT}")" \
  --force

rm -f "${CALLBACK_SCRIPT}"
info "✔ Secrets replaced in history blobs."

# ── Step 5: Commit .gitignore changes ────────────────────────────────────────
if ! git diff --quiet .gitignore 2>/dev/null || git ls-files --error-unmatch .gitignore >/dev/null 2>&1; then
  git add .gitignore
  git commit -m "sec: enforce Laravel security gitignore patterns [Capi Guard]" || true
  info "✔ .gitignore committed."
fi

# ── Step 6: Aggressive garbage collection ────────────────────────────────────
info "Running aggressive garbage collection..."
git reflog expire --expire=now --all
git gc --prune=now --aggressive
info "✔ Dangling objects purged."

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  ✔  Git history sanitized by Capi Guard               ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "NEXT STEPS:"
echo "  1. Rotate ALL exposed credentials (APP_KEY, DB_PASSWORD, API keys, IPs)"
echo "     php artisan key:generate"
echo "  2. Force-push to all remotes:"
echo "     git remote | xargs -I{} git push {} --force --all"
echo "     git remote | xargs -I{} git push {} --force --tags"
echo "  3. Notify all collaborators to re-clone the repository."
echo ""
